"""initial schema

Creates the 24 tables for the LiquorPriceBook MVP. The DDL is *frozen* here
rather than being generated from ``Base.metadata`` at runtime, so subsequent
ALTERs in later migrations can't be silently shadowed by model changes that
get backfilled into this migration on fresh databases.

If you change the model after this migration is shipped, write a new
migration with the explicit ``op.add_column`` / ``op.alter_column`` calls.
Do not edit this file.

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-19 12:00:00
"""

from typing import Sequence, Union

from alembic import op


revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SCHEMA_SQL = """
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE distributors (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    slug VARCHAR(64) NOT NULL,
    name VARCHAR(255) NOT NULL,
    state VARCHAR(2) DEFAULT 'NJ' NOT NULL,
    is_active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_distributors PRIMARY KEY (id),
    CONSTRAINT uq_distributors_slug UNIQUE (slug)
);

CREATE TABLE categories (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    slug VARCHAR(128) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    parent_id UUID,
    raw_aliases JSONB DEFAULT '[]'::jsonb NOT NULL,
    sort_order INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uq_categories_slug UNIQUE (slug),
    CONSTRAINT fk_categories_parent_id_categories
        FOREIGN KEY (parent_id) REFERENCES categories (id) ON DELETE SET NULL
);

CREATE TABLE brands (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    slug VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    raw_aliases JSONB DEFAULT '[]'::jsonb NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_brands PRIMARY KEY (id),
    CONSTRAINT uq_brands_slug UNIQUE (slug)
);

CREATE TABLE tenants (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    slug VARCHAR(128) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    clerk_org_id VARCHAR(128),
    plan VARCHAR(32) DEFAULT 'beta' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_tenants PRIMARY KEY (id),
    CONSTRAINT uq_tenants_slug UNIQUE (slug),
    CONSTRAINT uq_tenants_clerk_org_id UNIQUE (clerk_org_id)
);

CREATE TABLE audit_log (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    tenant_id UUID,
    user_id UUID,
    entity_table VARCHAR(64) NOT NULL,
    entity_id UUID NOT NULL,
    action VARCHAR(32) NOT NULL,
    before JSONB,
    after JSONB,
    at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_audit_log PRIMARY KEY (id),
    CONSTRAINT ck_audit_log_action_enum
        CHECK (action IN ('insert','update','delete','soft_delete','restore'))
);
CREATE INDEX ix_audit_log_entity ON audit_log (entity_table, entity_id);
CREATE INDEX ix_audit_log_tenant_at ON audit_log (tenant_id, at);

CREATE TABLE book_editions (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    distributor_id UUID NOT NULL,
    year INTEGER NOT NULL,
    month INTEGER NOT NULL,
    source_filename VARCHAR(512) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    storage_uri VARCHAR(1024),
    supersedes_id UUID,
    scraped_at TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_book_editions PRIMARY KEY (id),
    CONSTRAINT uq_book_editions_distributor_content_hash
        UNIQUE (distributor_id, content_hash),
    CONSTRAINT ck_book_editions_month_range CHECK (month BETWEEN 1 AND 12),
    CONSTRAINT ck_book_editions_year_range CHECK (year BETWEEN 2020 AND 2100),
    CONSTRAINT fk_book_editions_distributor_id_distributors
        FOREIGN KEY (distributor_id) REFERENCES distributors (id) ON DELETE RESTRICT,
    CONSTRAINT fk_book_editions_supersedes_id_book_editions
        FOREIGN KEY (supersedes_id) REFERENCES book_editions (id) ON DELETE SET NULL
);
CREATE INDEX ix_book_editions_distributor_year_month
    ON book_editions (distributor_id, year, month);

CREATE TABLE users (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    tenant_id UUID NOT NULL,
    clerk_user_id VARCHAR(128) NOT NULL,
    email VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),
    role VARCHAR(32) DEFAULT 'member' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT ck_users_role_enum CHECK (role IN ('owner','admin','member')),
    CONSTRAINT fk_users_tenant_id_tenants
        FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT uq_users_clerk_user_id UNIQUE (clerk_user_id)
);
CREATE INDEX ix_users_tenant_id ON users (tenant_id);

CREATE TABLE watchlists (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    tenant_id UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    is_default BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_watchlists PRIMARY KEY (id),
    CONSTRAINT fk_watchlists_tenant_id_tenants
        FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE INDEX ix_watchlists_tenant_id ON watchlists (tenant_id);

CREATE TABLE alert_configs (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    tenant_id UUID NOT NULL,
    rule_type VARCHAR(64) NOT NULL,
    params JSONB DEFAULT '{}'::jsonb NOT NULL,
    channel VARCHAR(32) DEFAULT 'email' NOT NULL,
    is_active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_alert_configs PRIMARY KEY (id),
    CONSTRAINT ck_alert_configs_channel_enum CHECK (channel IN ('email','sms','inapp')),
    CONSTRAINT fk_alert_configs_tenant_id_tenants
        FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
CREATE INDEX ix_alert_configs_tenant_id ON alert_configs (tenant_id);

CREATE TABLE ingest_runs (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    book_edition_id UUID NOT NULL,
    status VARCHAR(32) DEFAULT 'pending' NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE,
    finished_at TIMESTAMP WITH TIME ZONE,
    rows_by_section JSONB DEFAULT '{}'::jsonb NOT NULL,
    error JSONB,
    triggered_by_user_id UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_ingest_runs PRIMARY KEY (id),
    CONSTRAINT ck_ingest_runs_status_enum
        CHECK (status IN ('pending','running','completed','failed','superseded')),
    CONSTRAINT fk_ingest_runs_book_edition_id_book_editions
        FOREIGN KEY (book_edition_id) REFERENCES book_editions (id) ON DELETE CASCADE
);
CREATE INDEX ix_ingest_runs_status ON ingest_runs (status);

CREATE TABLE products (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    distributor_id UUID NOT NULL,
    code VARCHAR(32) NOT NULL,
    first_seen_in_edition_id UUID,
    last_seen_in_edition_id UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT uq_products_distributor_code UNIQUE (distributor_id, code),
    CONSTRAINT fk_products_distributor_id_distributors
        FOREIGN KEY (distributor_id) REFERENCES distributors (id) ON DELETE RESTRICT,
    CONSTRAINT fk_products_first_seen_in_edition_id_book_editions
        FOREIGN KEY (first_seen_in_edition_id) REFERENCES book_editions (id) ON DELETE SET NULL,
    CONSTRAINT fk_products_last_seen_in_edition_id_book_editions
        FOREIGN KEY (last_seen_in_edition_id) REFERENCES book_editions (id) ON DELETE SET NULL
);

CREATE TABLE combos (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    book_edition_id UUID NOT NULL,
    sku VARCHAR(32) NOT NULL,
    subcategory VARCHAR(64),
    item_code VARCHAR(255),
    contains TEXT,
    front_line_price NUMERIC(12, 2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_combos PRIMARY KEY (id),
    CONSTRAINT uq_combos_edition_sku UNIQUE (book_edition_id, sku),
    CONSTRAINT fk_combos_book_edition_id_book_editions
        FOREIGN KEY (book_edition_id) REFERENCES book_editions (id) ON DELETE CASCADE
);
CREATE INDEX ix_combos_sku ON combos (sku);

CREATE TABLE product_editions (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    product_id UUID NOT NULL,
    book_edition_id UUID NOT NULL,
    category_id UUID,
    brand_id UUID,
    raw_category VARCHAR(255),
    raw_brand_header VARCHAR(512),
    description TEXT,
    size VARCHAR(32),
    pack INTEGER,
    po_cost NUMERIC(12, 2),
    case_cost NUMERIC(12, 2),
    btl_cost NUMERIC(12, 2),
    best_buy_raw VARCHAR(64),
    best_rip_raw VARCHAR(128),
    page INTEGER,
    lane INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_product_editions PRIMARY KEY (id),
    CONSTRAINT uq_product_editions_product_edition UNIQUE (product_id, book_edition_id),
    CONSTRAINT fk_product_editions_product_id_products
        FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT fk_product_editions_book_edition_id_book_editions
        FOREIGN KEY (book_edition_id) REFERENCES book_editions (id) ON DELETE CASCADE,
    CONSTRAINT fk_product_editions_category_id_categories
        FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL,
    CONSTRAINT fk_product_editions_brand_id_brands
        FOREIGN KEY (brand_id) REFERENCES brands (id) ON DELETE SET NULL
);
CREATE INDEX ix_product_editions_category_id ON product_editions (category_id);
CREATE INDEX ix_product_editions_case_cost ON product_editions (case_cost);
CREATE INDEX ix_product_editions_brand_id ON product_editions (brand_id);
CREATE INDEX ix_product_editions_book_edition_id ON product_editions (book_edition_id);

CREATE TABLE partials_pricing (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    book_edition_id UUID NOT NULL,
    description TEXT NOT NULL,
    product_number VARCHAR(32),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    best_case_price NUMERIC(12, 2),
    best_case_tier VARCHAR(16),
    best_btl_price NUMERIC(12, 2),
    linked_product_id UUID,
    match_confidence NUMERIC(4, 3),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_partials_pricing PRIMARY KEY (id),
    CONSTRAINT fk_partials_pricing_book_edition_id_book_editions
        FOREIGN KEY (book_edition_id) REFERENCES book_editions (id) ON DELETE CASCADE,
    CONSTRAINT fk_partials_pricing_linked_product_id_products
        FOREIGN KEY (linked_product_id) REFERENCES products (id) ON DELETE SET NULL
);
CREATE INDEX ix_partials_pricing_dates ON partials_pricing (start_date, end_date);
CREATE INDEX ix_partials_pricing_linked_product ON partials_pricing (linked_product_id);

CREATE TABLE partials_rips (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    book_edition_id UUID NOT NULL,
    description TEXT NOT NULL,
    size VARCHAR(32),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    tier VARCHAR(16),
    rip_price NUMERIC(12, 2),
    rip_raw VARCHAR(128),
    linked_product_id UUID,
    match_confidence NUMERIC(4, 3),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_partials_rips PRIMARY KEY (id),
    CONSTRAINT fk_partials_rips_book_edition_id_book_editions
        FOREIGN KEY (book_edition_id) REFERENCES book_editions (id) ON DELETE CASCADE,
    CONSTRAINT fk_partials_rips_linked_product_id_products
        FOREIGN KEY (linked_product_id) REFERENCES products (id) ON DELETE SET NULL
);
CREATE INDEX ix_partials_rips_linked_product ON partials_rips (linked_product_id);
CREATE INDEX ix_partials_rips_dates ON partials_rips (start_date, end_date);

CREATE TABLE inventory_reduction (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    book_edition_id UUID NOT NULL,
    product_id UUID NOT NULL,
    subcategory VARCHAR(64),
    description TEXT,
    size VARCHAR(32),
    pack INTEGER,
    original_case NUMERIC(12, 2),
    original_bottle NUMERIC(12, 2),
    best_case NUMERIC(12, 2),
    best_bottle NUMERIC(12, 2),
    case_save NUMERIC(12, 2),
    bottle_save NUMERIC(12, 2),
    first_appeared_in_edition_id UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_inventory_reduction PRIMARY KEY (id),
    CONSTRAINT uq_inventory_reduction_edition_product UNIQUE (book_edition_id, product_id),
    CONSTRAINT fk_inventory_reduction_book_edition_id_book_editions
        FOREIGN KEY (book_edition_id) REFERENCES book_editions (id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory_reduction_product_id_products
        FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory_reduction_first_appeared_in_edition_id_boo_4403
        FOREIGN KEY (first_appeared_in_edition_id) REFERENCES book_editions (id) ON DELETE SET NULL
);
CREATE INDEX ix_inventory_reduction_product ON inventory_reduction (product_id);

CREATE TABLE combo_components (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    combo_id UUID NOT NULL,
    linked_product_id UUID,
    qty_cases INTEGER,
    qty_bottles INTEGER,
    raw_token TEXT NOT NULL,
    match_confidence NUMERIC(4, 3),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_combo_components PRIMARY KEY (id),
    CONSTRAINT fk_combo_components_combo_id_combos
        FOREIGN KEY (combo_id) REFERENCES combos (id) ON DELETE CASCADE,
    CONSTRAINT fk_combo_components_linked_product_id_products
        FOREIGN KEY (linked_product_id) REFERENCES products (id) ON DELETE SET NULL
);
CREATE INDEX ix_combo_components_combo ON combo_components (combo_id);

CREATE TABLE keg_list (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    book_edition_id UUID NOT NULL,
    type VARCHAR(16) NOT NULL,
    abg_code VARCHAR(32) NOT NULL,
    description TEXT NOT NULL,
    size VARCHAR(32),
    best_keg_price NUMERIC(12, 2),
    value_per_750ml NUMERIC(12, 2),
    best_btl_reg NUMERIC(12, 2),
    per_ounce_estimate NUMERIC(8, 4),
    in_stock BOOLEAN DEFAULT false NOT NULL,
    linked_product_id UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_keg_list PRIMARY KEY (id),
    CONSTRAINT uq_keg_list_edition_code UNIQUE (book_edition_id, abg_code),
    CONSTRAINT ck_keg_list_type_enum CHECK (type IN ('Deposit','Disposable')),
    CONSTRAINT fk_keg_list_book_edition_id_book_editions
        FOREIGN KEY (book_edition_id) REFERENCES book_editions (id) ON DELETE CASCADE,
    CONSTRAINT fk_keg_list_linked_product_id_products
        FOREIGN KEY (linked_product_id) REFERENCES products (id) ON DELETE SET NULL
);

CREATE TABLE watchlist_items (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    watchlist_id UUID NOT NULL,
    product_id UUID NOT NULL,
    target_case_price NUMERIC(12, 2),
    target_btl_price NUMERIC(12, 2),
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_watchlist_items PRIMARY KEY (id),
    CONSTRAINT uq_watchlist_items_watchlist_product UNIQUE (watchlist_id, product_id),
    CONSTRAINT fk_watchlist_items_watchlist_id_watchlists
        FOREIGN KEY (watchlist_id) REFERENCES watchlists (id) ON DELETE CASCADE,
    CONSTRAINT fk_watchlist_items_product_id_products
        FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE TABLE notes (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    tenant_id UUID NOT NULL,
    product_id UUID NOT NULL,
    author_user_id UUID,
    body TEXT NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_notes PRIMARY KEY (id),
    CONSTRAINT fk_notes_tenant_id_tenants
        FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT fk_notes_product_id_products
        FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT fk_notes_author_user_id_users
        FOREIGN KEY (author_user_id) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX ix_notes_tenant_product ON notes (tenant_id, product_id);

CREATE TABLE alert_events (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    tenant_id UUID NOT NULL,
    alert_config_id UUID,
    product_id UUID,
    book_edition_id UUID,
    rule_type VARCHAR(64) NOT NULL,
    score NUMERIC(4, 3),
    payload JSONB DEFAULT '{}'::jsonb NOT NULL,
    read_at TIMESTAMP WITH TIME ZONE,
    fired_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_alert_events PRIMARY KEY (id),
    CONSTRAINT fk_alert_events_tenant_id_tenants
        FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT fk_alert_events_alert_config_id_alert_configs
        FOREIGN KEY (alert_config_id) REFERENCES alert_configs (id) ON DELETE SET NULL,
    CONSTRAINT fk_alert_events_product_id_products
        FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE SET NULL,
    CONSTRAINT fk_alert_events_book_edition_id_book_editions
        FOREIGN KEY (book_edition_id) REFERENCES book_editions (id) ON DELETE SET NULL
);
CREATE INDEX ix_alert_events_tenant_fired_at ON alert_events (tenant_id, fired_at);

CREATE TABLE ai_verdict_cache (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    product_id UUID NOT NULL,
    book_edition_id UUID NOT NULL,
    verdict VARCHAR(16) NOT NULL,
    confidence NUMERIC(4, 3) NOT NULL,
    rationale TEXT NOT NULL,
    factors JSONB DEFAULT '{}'::jsonb NOT NULL,
    model VARCHAR(64) NOT NULL,
    generated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_ai_verdict_cache PRIMARY KEY (id),
    CONSTRAINT uq_ai_verdict_product_edition UNIQUE (product_id, book_edition_id),
    CONSTRAINT ck_ai_verdict_cache_verdict_enum
        CHECK (verdict IN ('BUY_NOW','DEFER','HOLD','PASS')),
    CONSTRAINT fk_ai_verdict_cache_product_id_products
        FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_verdict_cache_book_edition_id_book_editions
        FOREIGN KEY (book_edition_id) REFERENCES book_editions (id) ON DELETE CASCADE
);

CREATE TABLE low_confidence_matches (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    book_edition_id UUID NOT NULL,
    source_table VARCHAR(64) NOT NULL,
    source_id UUID NOT NULL,
    candidate_product_id UUID,
    confidence NUMERIC(4, 3) NOT NULL,
    payload JSONB DEFAULT '{}'::jsonb NOT NULL,
    resolved_at TIMESTAMP WITH TIME ZONE,
    resolved_to_product_id UUID,
    resolved_by_user_id UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_low_confidence_matches PRIMARY KEY (id),
    CONSTRAINT fk_low_confidence_matches_book_edition_id_book_editions
        FOREIGN KEY (book_edition_id) REFERENCES book_editions (id) ON DELETE CASCADE,
    CONSTRAINT fk_low_confidence_matches_candidate_product_id_products
        FOREIGN KEY (candidate_product_id) REFERENCES products (id) ON DELETE SET NULL,
    CONSTRAINT fk_low_confidence_matches_resolved_to_product_id_products
        FOREIGN KEY (resolved_to_product_id) REFERENCES products (id) ON DELETE SET NULL,
    CONSTRAINT fk_low_confidence_matches_resolved_by_user_id_users
        FOREIGN KEY (resolved_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX ix_low_confidence_matches_unresolved
    ON low_confidence_matches (book_edition_id) WHERE resolved_at IS NULL;
CREATE INDEX ix_low_confidence_matches_book_edition
    ON low_confidence_matches (book_edition_id);

CREATE TABLE rip_offers (
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    product_edition_id UUID NOT NULL,
    tier VARCHAR(16) NOT NULL,
    tier_cases INTEGER NOT NULL,
    save_amount NUMERIC(12, 2) NOT NULL,
    case_price NUMERIC(12, 2),
    btl_price NUMERIC(12, 2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_rip_offers PRIMARY KEY (id),
    CONSTRAINT uq_rip_offers_edition_tier UNIQUE (product_edition_id, tier),
    CONSTRAINT ck_rip_offers_tier_cases_positive CHECK (tier_cases > 0),
    CONSTRAINT ck_rip_offers_nj_50_case_cap CHECK (tier_cases <= 50),
    CONSTRAINT ck_rip_offers_nj_1000_dollar_cap
        CHECK (save_amount >= 0 AND save_amount <= 1000),
    CONSTRAINT fk_rip_offers_product_edition_id_product_editions
        FOREIGN KEY (product_edition_id) REFERENCES product_editions (id) ON DELETE CASCADE
);
CREATE INDEX ix_rip_offers_product_edition_id ON rip_offers (product_edition_id);

-- Trigram search indexes on free-text columns.
CREATE INDEX IF NOT EXISTS ix_product_editions_description_trgm
    ON product_editions USING gin (description gin_trgm_ops);
CREATE INDEX IF NOT EXISTS ix_combos_contains_trgm
    ON combos USING gin (contains gin_trgm_ops);
""".strip()


_DOWN_TABLES = [
    # reverse-dependency order
    "rip_offers",
    "low_confidence_matches",
    "ai_verdict_cache",
    "alert_events",
    "notes",
    "watchlist_items",
    "keg_list",
    "combo_components",
    "inventory_reduction",
    "partials_rips",
    "partials_pricing",
    "product_editions",
    "combos",
    "products",
    "ingest_runs",
    "alert_configs",
    "watchlists",
    "users",
    "book_editions",
    "audit_log",
    "tenants",
    "brands",
    "categories",
    "distributors",
]


def upgrade() -> None:
    op.execute(SCHEMA_SQL)


def downgrade() -> None:
    for t in _DOWN_TABLES:
        op.execute(f"DROP TABLE IF EXISTS {t} CASCADE")
